apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-ds
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST

  - name: ClickHouse
    uid: clickhouse-ds
    type: grafana-clickhouse-datasource
    access: proxy
    editable: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: estate
      username: ${CLICKHOUSE_USER}
      tlsSkipVerify: true
    secureJsonData:
      password: ${CLICKHOUSE_PASSWORD}
